server:
  port: 9090
  ip: 47.109.58.84
#  ip: localhost

spring:
  springfox:
    documentation:
      swagger-ui:
        enabled : true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.109.58.84:3306/WebHomeWork?serverTimezone=GMT%2b8

mybatis:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
  #  path: E:/MyVue/files/
    path: /home/files/




